### ISSUE TITLE
adding count

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe-labs/silverstripe-reports#1]
Hi

I am wondering if you can add the following to reports:

//report line 130

	/**
	 * counts the number of objects returned
	 * @param Array $params - any parameters for the sourceRecords
	 * @return Int
	 */
	public function getCount($params = array()){
		$sourceRecords = $this->sourceRecords($params, null, null);
		if(!$sourceRecords instanceOf SS_List){
			user_error($this->class."::sourceRecords does not return an SS_List");
		}
		return $sourceRecords->count();
	}

	reportadmin line 168:

			$columns->setFieldFormatting(array(
				'title' => '<a href=\"$Link\" class=\"cms-panel-link\">$value ($Count)</a>'
			));

This will add a count for each report which is immensely useful in working out what reports need attention without opening all of them..... in a next phase, it might also be an idea to add "needs attention" levels... where reports with a certain count (e.g. brokenLinks.Count > 0) will turn red in list or something like that.

**Comment by dhensby** [comment]
Fixed
