### ISSUE TITLE
Latest commit (fc81b1f) makes admin view crash

### ISSUE THREAD

**Issue by phil-quinn** [silverstripe-labs/silverstripe-reports#24]
Hi @tractorcow,

Your latest commit (fc81b1f) which is picked up by a routine composer update, is making the admin crash. Works fine without the changes in the commit.

Is the branch that is getting picked up in a normal composer update the stable one?

Here is the error I am seeing.

[User Error] Uncaught Exception: Object->__call(): the method 'extendedcan' does not exist on 'BrokenFilesReport'
GET /admin/pages
Line 739 in /usr/home/vagrant/Project/docroot/framework/core/Object.php
Source
730 				default :
731 					throw new Exception (
732 						"Object->__call(): extra method $method is invalid on $this->class:"
733 							. var_export($config, true)
734 					);
735 			}
736 		} else {
737 			// Please do not change the exception code number below.
738 			$class = get_class($this);
739 			throw new Exception("Object->__call(): the method '$method' does not exist on '$class'", 2175);
740 		}
741 	}
742 
743 	// --------------------------------------------------------------------------------------------------------------
744 
745 	/**
Trace
Object->__call(extendedCan,Array) 
Report.php:312
BrokenFilesReport->extendedCan(canView,Member) 
Report.php:312
SS_Report->canView() 
ReportAdmin.php:89
ReportAdmin->Reports() 
ReportAdmin.php:73
ReportAdmin->canView(Member) 
CMSMenu.php:200
CMSMenu::get_viewable_menu_items() 
LeftAndMain.php:625
LeftAndMain->MainMenu() 
ViewableData.php:402
ViewableData->obj(MainMenu,,1,,) 
SSViewer.php:91
SSViewer_Scope->getObj(MainMenu,,1,,) 
SSViewer.php:525
SSViewer_DataPresenter->getObj(MainMenu,,1,,) 
SSViewer.php:111
SSViewer_Scope->obj(MainMenu,,1) 
.cache.framework.admin.templates.Includes.LeftAndMain_Menu.ss:96
include(/usr/home/vagrant/Project/docroot/silverstripe-cache/vagrant/.cache.framework.admin.templates.Includes.LeftAndMain_Menu.ss) 
SSViewer.php:1059
SSViewer->includeGeneratedTemplate(/usr/home/vagrant/Project/docroot/silverstripe-cache/vagrant/.cache.framework.admin.templates.Includes.LeftAndMain_Menu.ss,CMSPagesController,,Array,) 
SSViewer.php:1119
SSViewer->process(CMSPagesController,) 
ViewableData.php:341
ViewableData->renderWith(Array) 
LeftAndMain.php:699
LeftAndMain->Menu() 
ViewableData.php:402
ViewableData->obj(Menu,,,1) 
ViewableData.php:475
ViewableData->XML_val(Menu,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:550
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.framework.admin.templates.LeftAndMain.ss:37
SSViewer_DataPresenter->XML_val(Menu,,1) 
.cache.framework.admin.templates.LeftAndMain.ss:37
include(/usr/home/vagrant/Project/docroot/silverstripe-cache/vagrant/.cache.framework.admin.templates.LeftAndMain.ss) 
SSViewer.php:1059
SSViewer->includeGeneratedTemplate(/usr/home/vagrant/Project/docroot/silverstripe-cache/vagrant/.cache.framework.admin.templates.LeftAndMain.ss,CMSPagesController,,Array,) 
SSViewer.php:1119
SSViewer->process(CMSPagesController,) 
ViewableData.php:341
ViewableData->renderWith(SSViewer) 
LeftAndMain.php:599
LeftAndMain->{closure}() 
call_user_func(Closure) 
PjaxResponseNegotiator.php:82
PjaxResponseNegotiator->respond(SS_HTTPRequest) 
LeftAndMain.php:505
LeftAndMain->index(SS_HTTPRequest) 
CMSMain.php:126
CMSMain->index(SS_HTTPRequest) 
RequestHandler.php:288
RequestHandler->handleAction(SS_HTTPRequest,index) 
Controller.php:200
Controller->handleAction(SS_HTTPRequest,index) 
RequestHandler.php:200
RequestHandler->handleRequest(SS_HTTPRequest,DataModel) 
Controller.php:157
Controller->handleRequest(SS_HTTPRequest,DataModel) 
LeftAndMain.php:451
LeftAndMain->handleRequest(SS_HTTPRequest,DataModel) 
AdminRootController.php:93
AdminRootController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:385
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:149
Director::direct(/admin/pages,DataModel) 
main.php:184

**Comment by tractorcow** [comment]
Ugh, no wonder. It's a ViewableData not a DataObject. I'll have to patch an emergency fix to it.

**Comment by oddnoc** [comment]
This is because the CMS module asks for reports version ~3.2, which will pull in the tip of the 3.2 branch. Shall we submit a pull request to change cms's composer.json to ask for ^3.2, which will adhere more strictly to semver?

**Comment by phil-quinn** [comment]
Thanks @tractorcow!

**Comment by tractorcow** [comment]
I don't think that ~3.2 and ^3.2 actually differ; Both mean <4,>=3.2.0.

There's a fix at https://github.com/silverstripe-labs/silverstripe-reports/pull/25/files

We've discussed not bothering to have a different 3.2 and 3.3 version; @dhensby :) Maybe now we should make that change?

**Comment by oddnoc** [comment]
@tractorcow The documentation does imply that ~3.2 and ^3.2 have the same definition, but operationally, they don't. ~3.2 will pick up the tip of the 3.2 branch. ^3.2 will only pick up tags.

**Comment by tractorcow** [comment]
Oh, that's good to know!

I recall reading that ~ matches -beta tags as well. I should probably make sure any future beta releases use this instead of ^. ;)
